spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.99.101:3306/sboot_study?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell

wechat:
  mpAppId: wx9f411674d201707a
  mpAppSecrect: 2a5a83af8be62a2c69ce198f0c046c5e